sudo: false
language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.0
services:
  - postgresql
before_script:
  - mix local.hex --force
  - mix deps.get --force
  - mix ecto.create
  - mix ecto.migrate
script:
  - mix test --trace
