use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :grid, Grid.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "book.outpostjh.com", port: 80],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")

config :grid,
  tripadvisor_api_key: {:system, "TRIPADVISOR_API_KEY"},
  booking_emails_bcc: "book@outpostjh.com",
  notify_vendors: true,
  prerender_service_url: "https://service.prerender.io",
  prerender_service_token: System.get_env("PRERENDER_TOKEN")


# Do not print debug messages in production
config :logger,
  level: :info,
  handle_otp_reports: true,
  handle_sasl_reports: true

config :logger,
  backends: [:console, Rollbax.Notifier]

config :arc, bucket: "outpost-grid"

config :grid, Grid.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: 20
